/*
 * Regenerates the inlined icon set in styles.css.
 *
 * The page draws Bootstrap Icons as CSS masks instead of loading the icon font
 * (86 KB of CSS + a 127 KB WOFF2 for the 29 glyphs actually used). This script
 * scans index.html and script.js for `bi-*` class names, downloads those SVGs
 * from the CDN, and rewrites the block between the sentinels in styles.css.
 *
 * Run after adding or removing an icon:
 *   node tools/build-icons.js
 */

const fs = require('fs');
const path = require('path');
const https = require('https');

const VERSION = '1.11.3';
const ROOT = path.join(__dirname, '..');
const START = '/* icons:start */';
const END = '/* icons:end */';

const read = (f) => fs.readFileSync(path.join(ROOT, f), 'utf8');

const names = [
  ...new Set(
    [...(read('index.html') + read('script.js')).matchAll(/\bbi-[a-z0-9-]+/g)].map((m) => m[0])
  ),
]
  .map((c) => c.slice(3))
  .sort();

const get = (url) =>
  new Promise((resolve, reject) => {
    https
      .get(url, (res) => {
        if (res.statusCode !== 200) return reject(new Error(`${res.statusCode} ${url}`));
        let body = '';
        res.on('data', (c) => (body += c));
        res.on('end', () => resolve(body));
      })
      .on('error', reject);
  });

/* A mask reads the alpha channel, so the paint only has to be opaque;
   currentColor would stay unresolved inside a data URI. */
const toDataUri = (svg) =>
  svg
    .replace(/\s*(width|height|class)="[^"]*"/g, '')
    .replace(/fill="currentColor"/g, 'fill="black"')
    .replace(/<!--[\s\S]*?-->/g, '')
    .replace(/\s+/g, ' ')
    .trim()
    .replace(/"/g, "'")
    .replace(/%/g, '%25')
    .replace(/</g, '%3C')
    .replace(/>/g, '%3E')
    .replace(/#/g, '%23')
    .replace(/&/g, '%26');

(async () => {
  const rules = [];
  for (const name of names) {
    const svg = await get(
      `https://cdn.jsdelivr.net/npm/bootstrap-icons@${VERSION}/icons/${name}.svg`
    );
    rules.push(`.bi-${name} {\n  --bi: url("data:image/svg+xml,${toDataUri(svg)}");\n}`);
  }

  const block = `${START}
/* Generated by tools/build-icons.js - do not edit by hand.
   Bootstrap Icons v${VERSION}, ${rules.length} glyphs, drawn as masks so that
   <i class="bi bi-name"> keeps working with no font request. The glyph takes
   its colour from currentColor and its size from font-size, exactly like the
   font did. */

.bi::before,
[class^='bi-']::before,
[class*=' bi-']::before {
  content: '';
  display: inline-block;
  width: 1em;
  height: 1em;
  line-height: 1;
  vertical-align: -0.125em;
  background-color: currentColor;
  -webkit-mask: var(--bi) center / contain no-repeat;
  mask: var(--bi) center / contain no-repeat;
}

${rules.join('\n')}
${END}`;

  const cssPath = path.join(ROOT, 'styles.css');
  const css = fs.readFileSync(cssPath, 'utf8');
  const from = css.indexOf(START);
  const to = css.indexOf(END);
  if (from === -1 || to === -1) {
    throw new Error(`sentinels ${START} / ${END} not found in styles.css`);
  }

  fs.writeFileSync(cssPath, css.slice(0, from) + block + css.slice(to + END.length));
  console.log(`styles.css updated: ${rules.length} icons, ${(block.length / 1024).toFixed(1)} KB`);
})().catch((err) => {
  console.error(err.message);
  process.exit(1);
});
